- name: install common
  become: yes
  pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - expect
    - git
    - tree
    - vim
    - zsh
    - chrome-gnome-shell
    
 
 - name: install theme
  become: yes
  pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - ttf-fira-code
    - powerline-fonts
    - adobe-source-code-pro-fonts

- name: install fonts
  become: yes
  pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - ttf-fira-code
    - powerline-fonts
    - adobe-source-code-pro-fonts

- name: install input method
  become: yes
  pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - ibus-rime