- name: add docker-ce key
  become: yes
  pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - docker
    - docker-compose
    
- name: install jdk packages
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - jdk-openjdk
    - jdk8-openjdk    



- name: install code packages
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - code   


- name: install jdk packages
  become: yes
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - yarn  
 