- name: install packages from repo
  become: yes
  pacman:
    name: 
      - evolution
      - evolution-ews
      - filezilla
      - guake
      - keepassxc  
      - terminator
      - shadowsocks-libev
      - zeal
      - hyper
      - jq
    state: present
    
 
 